name: dr_booking_flu
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluttie: ^0.5.0
  auto_size_text: ^2.1.0
  provider: ^3.2.0
  cuberto_bottom_bar: ^1.0.0
  circular_bottom_navigation: ^1.0.1
  circle_bottom_navigation: ^1.0.5
  page_indicator: ^0.3.0
  material_design_icons_flutter: ^3.4.4895
  http: ^0.12.0+2
  flutter_rating_bar: ^3.0.1+1
  progress_dialog: ^1.2.0
  flutter_custom_dialog: ^1.0.16
  shared_preferences: ^0.5.3
  progress_hud: ^1.1.0
  flutter_progress_hud: ^1.0.2
  google_maps_flutter: ^0.5.21+14
  loading: ^1.0.2
  toast: ^0.1.5
  shimmer: ^1.1.0
  fancy_shimmer_image: ^1.0.0
  fancy_bottom_navigation: ^0.3.2
  fancy_dialog: ^1.0.3
  connectivity: ^0.4.6
  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - animations/welcome.json
    - animations/community.json
    - animations/idea.json
    - animations/success.json
    - images/drbooking.png
    - images/booking.png
    - images/medica.jpg
    - images/medicc.png
    - images/selectdoc.png
    - images/book_doc.png
    - images/selectdoc.png
    - images/choose_doc.png
    - images/patient.png
    - images/choose.png
    - images/person.png
    - images/person_user.png
    - images/link.png
    - images/gender.png
    - images/nxt_page.png
    - images/calendar.png
    - images/favourites.png
    - images/hear.png
    - images/phone.png
    - images/email.png
    - images/all_docs_loading.png
    - images/error_login.png
    - images/sad.png
    - images/suceess_login.png
    - images/no_data_found.png
    - images/ticket.png
    - images/tick.png
    - images/anim.gif
    - images/pencil.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: thesansbold
      fonts:
        - asset: fonts/thesansbold.otf
        - weight: 700


    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
